apiVersion: mytracks4mac.info/v1
kind: ComplexJob
metadata:
  name: somejob
spec:
  pods:
    - name: pod1
      spec:
        containers:
        - name: job
          image: nginx
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          ports:
          - containerPort: 80
    - name: pod2
      spec:
        initContainers:
        - name: sleep
          image: busybox
          command:
            - "sleep"
            - "10"
          env:
          - name: SOME_URL
            value: "http://{POD1_POD_IP}:12345"
        containers:
        - name: job
          image: nginx
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          ports:
          - containerPort: 80
          env:
          - name: ExistingEnv
            value: "12345"
    - name: pod3
      spec:
        containers:
        - name: job
          image: nginx
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
          ports:
          - containerPort: 80
          env:
          - name: ExistingEnv1
            value: "12345"
          - name: SOME_IP
            value: "{$POD2_POD_IP}"
